spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver


  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: create

    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    lettuce:
    host: localhost
    port: 6379
  jwt:
    secret: N1Y8VjG7aKNHXbPR1Pqa6FIBo9S5oy3zGEP6ErJ1P5Ua
    expiration: 1800000

  # Email
  #
  mail:
    host: smtp.gmail.com
    port: 587
    username: hwangdonggeun70@gmail.com
    password:

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 120  # 30 * 60 * 1000 == 30?
#server:
 # http2:
  #  enabled: true
  #ssl:

   # key-store-type: PKCS12
   # key-store: src/main/resources/keystore.p12
   # key-store-password: 1234!@
   # key-alias: linemac-ssl

  servlet:
    session:
       timeout: 1800
       cookie:
        http-only: true
        path: /
        secure: true
        domain: localhost
        same-site: none

mybatis:
  type-aliases-package: com.example.posttest.dtos, com.example.posttest.entitiy
  #type-aliases-package는 여러개가 등록이된다.
  configuration:
    map-underscore-to-camel-case: false

#logging:
 # level:
  #  org:
   #   springframework:
    #    transaction:
     #     interceptor: trace

#logging:
 # level:
  #  org.springframework.messaging: DEBUG
   # org.springframework.web.socket: DEBUG
    #org.springframework.web.socket.client: DEBUG
    #org.springframework.web.socket.messaging: DEBUG
