spring:
  config:
    import: optional:classpath:env.yml
  data:
    redis:
      host: localhost
      port: 6379
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: ${DATA_BASE_URL}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: postgres
    password: dong3058!
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  jwt:
    secret: N1Y8VjG7aKNHXbPR1Pqa6FIBo9S5oy3zGEP6ErJ1P5Ua
    expiration: 60000
  redis:
    lettuce:
    host: localhost
    port: 6379
  # Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: hwangdonggeun70@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 120  # 30 * 60 * 1000 == 30?
server:
  servlet:
    session:
      timeout: 1800
      cookie:
        http-only: true
        path: /
        secure: true
        domain: ".mywikiback.shop"
        #.compute.amazonaws.com
        #An invalid domain [.ec2-43-203-242-68.ap-northeast                    -2.compute.amazonaws.com] was specified for this cookie
        #라는 에러가뜨는대 알보고니 ip가들어가는애들은 슬수가없다고한다 그래서 뒤의 compute~~만남기도 하위도메인개념으로 .을 넣어줫다 . httpsession생ㅅ어중에 만난 오류이다!
        same-site: strict


cloud:
  host:
    url: ${AWS_EC2_URL}
    port: 8080









